package org.ird.unfepi.constants;

public enum EncounterType 
{
	ENROLLMENT,
	FOLLOWUP,
	FOLLOWUP_ADMIN,
	SCREENING,
	DAILY_SUMMARY,
	ADD_CONTACT_NUM,
	CHANGE_PREFERENCE,
	VACCINATOR_REG,
	STOREKEEPER_REG,
	VACC_CENTER_REG,
	LOTTERY_GEN,
	STK_INCENTIVIZE,
	VACC_INCENTIVIZE,
	LOTTERY_CONSUMP,
	VACCINE_REG
}