<htmlform>
	<!-- Autogenerated example form  (template from 01-Nov-2010 -->
	<macros>
		paperFormId = (Fill this in)
		headerColor =#415E92
		fontOnHeaderColor = white
	</macros>
<style>
.biginput input{
height: 50px;
width: 300px;
}

.biglonginput input, textarea{
height: 30px;
width: 90%;
}

table.designtable {
width: 1100px !important;
border: solid 1px silver;
}
table.designtable td{
padding-right: 0px !important;
border: solid 1px #FBEFF2;
border-collapse: collapse !important;
empty-cells: show;
}
.designtable td{
padding-right: 0px !important;
border: solid 1px #FBEFF2;
border-collapse: collapse;
empty-cells: show;
}
.rule td{
border-bottom: solid 1px silver !important;
}
.noborder td{
border: none !important;
}
</style>
	<h1 align="center">${uimessage('codbr.deathCertificate')}</h1>
	<div class="designtable">
	<table class="designtable">
		<tr class="noborder">
			<td/>
			<td/>
			<td>${uimessage('codbr.identifier')}</td>
			<td>
				<lookup expression="patient.getPatientIdentifier(3)"/>
				<encounterDate default="today" id="date"/>
				<encounterProvider default="currentUser" id="user"/>
				<span  style="display:none">
				<encounterLocation type="autocomplete" default="1" style="display:none"/></span>
			</td>
		</tr>
		<tr class="noborder">
			<td/>
			<td/>
			<td>${uimessage('codbr.hospitalName')}</td>
			<td>
				<obs conceptId="163103"/>
			</td>
		</tr>
		<tr class="noborder">
			<td/>
			<td/>
			<td>${uimessage('codbr.fiscalYear')}</td>
			<td>
				<obs conceptId="163104"/>
			</td>
		</tr>
		<tr class="noborder">
			<td/>
			<td/>
			<td>
				<div class="questioncnt">${uimessage('codbr.deathCertificateNo')}</div>
			</td>
			<td>
				<obs conceptId="162052"/>
			</td>
		</tr>
		<tr>
			<td colspan="100" class="sectionHeader">
				<h4>${uimessage('codbr.DeathCertificate.administrativeInformation')}</h4>
			</td>
		</tr>
		<tr>
			<td colspan="2">${uimessage('codbr.DeathCertificate.deathNumber')}</td>
			<td colspan="2">
				<obs conceptId="162182" />
			</td>
		</tr>			
		<tr>
			<td colspan="2">${uimessage('codbr.DeathCertificate.legalName')}</td>
			<td colspan="2"  class="biglonginput">
				<input/>
			</td>
		</tr>
		<tr/>
		<tr>
			<td>${uimessage('codbr.sex')}</td>
			<td colspan="3">
				<patient field="gender"/>
			</td>
		</tr>
		<tr>
			<td>${uimessage('codbr.dateOfBirthNepali')} <span style="float: right;">(BS)</span></td> 
			<td>
			<obs conceptId="163062" class="nepaliDate" id="birthDateNepali"/>
			</td>
			<td>${uimessage('codbr.dateOfDeathNepali')} <span style="float: right;">(BS)</span></td>
			<td><obs conceptId="163114" class="nepaliDate" id="deathDateNepali" /></td>
		</tr>
		
		<tr>
			<td><span style="float: right;">(AD)</span></td> 
			<td>
			<obs conceptId="163123" id="birthDate"/>
			</td>
			<td><span style="float: right;">(AD)</span></td>
			<td><obs conceptId="1543" id="deathDate"/></td>
		</tr>
		<tr>
			<td>
				<p id="ageYear"/>
			</td>
		</tr>
		<tr>
			<td>${uimessage('codbr.deathTime')}</td>
			<td>
				<obs conceptId="163115"/>
			</td>
		</tr>
		<tr>
			<td>${uimessage('codbr.fatherName')}</td>
			<td>
				<obs conceptId="1594"/>
			</td>
			<td>${uimessage('codbr.motherName')}</td>
			<td>
				<obs conceptId="1593"/>
			</td>
		</tr>
		<tr>
			<td>${uimessage('codbr.spouseName')}</td>
			<td>
				<obs conceptId="163077"/>
			</td>
		</tr>
		<tr><td colspan="4">
				<h3 style="margin-right: -20px">${uimessage('codbr.Address')}</h3>
			</td>
		</tr>
		<tr >
			<td colspan="4" >
			</td>
		</tr>
		<tr class="noborder">
			<td>${uimessage('codbr.Address.country')}</td>
			<td>
				<obs conceptId="162305" />
			</td>
			<td>${uimessage('codbr.Address.countyDistrict')}</td>
			<td>
				<obs conceptId="162319" />
			</td>
		</tr>
		<tr class="noborder">
			<td>${uimessage('codbr.Address.cityVillage')}</td>
			<td colspan="3">
				<obs conceptId="162308" class="biglonginput"/>
			</td>
		</tr>
		<tr class="noborder">
			<td>${uimessage('codbr.Address.address5')}</td>
			<td>
				<obs conceptId="163036" />
			</td>
			<td>${uimessage('codbr.Address.address6')}</td>
			<td>
				<obs conceptId="163058" />
			</td>
		</tr>
		<tr >
			<td colspan="4" >
			</td>
		</tr>
		<tr>
			<td>${uimessage('codbr.Death.declaredBy')}</td>
			<td colspan="3">
				<obs conceptId="163116" class="biglonginput"/>
			</td>
		</tr>
		<tr>
			<td colspan="100" class="sectionHeader">
				<h4>${uimessage('codbr.DeathCertificate.medicalInformation')}</h4>
			</td>
		</tr>
		<tr>
		<td colspan="4">
		<table class="designtable" border="0px" width="100%" >
		<tr>
			<th>${uimessage('codbr.partI')}</th>
			<td>${uimessage('codbr.causeOfDeath')}</td>
			<td>${uimessage('codbr.timeToDeath')}</td>
		</tr>
		<tr>
			<td >${uimessage('codbr.DeathCertificate.reportDisease')}</td>
			<td>A <obs conceptId="163020"  style="autocomplete" class="biginput"/>
			</td>
			<td colspan="2">
				<obs conceptId="162190"  />
				<obs conceptId="162189" />
			</td>            
		</tr>
		<tr>
			<td >${uimessage('codbr.DeathCertificate.reportChain')}</td>
			<td>B <obs conceptId="163021"  style="autocomplete"  class="biginput"/>
			</td>
			<td colspan="2">
				<obs conceptId="162190"  rows="2" cols="25"/>
				<obs conceptId="162189" />
			</td>            
		</tr>
		<tr>
			<td >${uimessage('codbr.DeathCertificate.underlyingCause')}</td>
			<td>C <obs conceptId="163022"  style="autocomplete"  class="biginput"/>
			</td>
			<td colspan="2">
				<obs conceptId="162190"/>
				<obs conceptId="162189"/>
			</td> 
		</tr>         
		<tr>
			<td/>
			<td>D <obs conceptId="163023"  style="autocomplete"  class="biginput"/>
			</td>
			<td colspan="2">
				<obs conceptId="162190"/>
				<obs conceptId="162189"/>
			</td>   
		</tr>
		</table>
		</td>
		</tr>
		<tr>
			<th>${uimessage('codbr.partII')}</th>
		</tr>
		<tr>
		<td colspan="4">
		<table>
		<tr>
			<td>${uimessage('codbr.DeathCertificate.otherConditions')}</td>
			<td colspan="2">
				<obs conceptId="160220" class="biginput"/>
			</td>
		</tr>
		</table>
		</td>
		</tr>
		<tr>
			<td >${uimessage('codbr.DeathCertificate.surgery')}</td>
			<td colspan="2">
				<obs conceptId="162191" answerConceptIds="1065,1066,1067"  id="surgery" />
			</td>
		</tr>
		<tr parent-dependancy="parent:surgery,requiredText:yes,action:show,resetField:surgery_date">
			<td >${uimessage('codbr.DeathCertificate.surgeryDate')}</td>
			<td colspan="2">
				<obs class="obsTagcls" conceptId="162192" id="surgery_date"/>
			</td>
		</tr>
		<tr  parent-dependancy="parent:surgery,requiredText:yes,action:show,resetField:surgery_reason">
			<td >${uimessage('codbr.DeathCertificate.surgeryReason')}</td>
			<td colspan="2">
				<obs class="obsTagcls" conceptId="162193" style="textarea" id="surgery_reason" />
			</td>
		</tr>
		<tr>
			<td >${uimessage('codbr.DeathCertificate.autopsyRequired')}</td>
			<td colspan="2">
				<obs conceptId="162194" answerConceptIds="1065,1066,1067"  />
			</td>
		</tr>
		<tr>
			<td >${uimessage('codbr.DeathCertificate.certification')}</td>
			<td colspan="2">
				<obs conceptId="162195" answerConceptIds="1065,1066,1067"  />
			</td>
		</tr>
		<tr>
			<td colspan="100" class="sectionHeader">
				<h4>${uimessage('codbr.DeathCertificate.deathDueTo')}</h4>
			</td>
		</tr>
		<tr>
			<td colspan="4">
				<obs conceptId="162196" answerConceptIds="162197,121387,123809,119964,162198,162199,158754,162200,1067" style="radio"  />
			</td>
		</tr>
		<tr>
			<th>${uimessage('codbr.DeathCertificate.externalCause')}</th>
			<td>${uimessage('codbr.DeathCertificate.injuryDate')}</td>
			<td colspan="2">
				<obs conceptId="162202"/>
			</td>
		</tr>
		<tr>
			<td colspan="2">${uimessage('codbr.DeathCertificate.externalCauseOccurrence')}</td>
			<td colspan="2">
				<obs conceptId="162201" style="textarea"/>
			</td> 
		</tr>
		<tr>
			<td colspan="100" class="sectionHeader">
				<h4>${uimessage('codbr.DeathCertificate.placeOfOccurrence')}</h4>
			</td>
		</tr>
		<tr>
			<td colspan="4">
				<obs conceptId="1541" answerConceptIds="150335,130137,159928,150352,130136,162205,130144,130145,5622,1067" style="radio"/>
			</td>
		</tr>
		<tr>
			<td colspan="100" style="padding: 0px 0px !important">
				<table class="patientName" id="foetal">
					<tr>
						<td colspan="100" class="sectionHeader">
							<h4>${uimessage('codbr.DeathCertificate.fetalOrInfantDeath')}</h4>
						</td>
					</tr>
					<tr>
						<td>${uimessage('codbr.DeathCertificate.multiplePregnancy')}</td>
						<td colspan="2">
							<obs conceptId="162191" answerConceptIds="1065,1066,1067" />
						</td>
					</tr>
					<tr>
						<td>${uimessage('codbr.DeathCertificate.stillBorn')}</td>
						<td colspan="2">
							<obs conceptId="162191" answerConceptIds="1065,1066,1067" />
						</td>
					</tr>
					<tr>
						<td>${uimessage('codbr.DeathCertificate.completedWeeksOfPregnancy')}</td>
						<td>
							<obs conceptId="1409"/>
						</td>
						<td>${uimessage('codbr.birthWeight')}</td>
						<td>
							<obs conceptId="162206"/>
						</td>
					</tr>
					<tr>
						<td colspan="2">${uimessage('codbr.motherAgeYear')}</td>
						<td colspan="2">
							<obs conceptId="1868" />
						</td>
					</tr>
					<tr>
						<td colspan="2">${uimessage('codbr.DeathCertificate.perinatalDeath')}</td>
						<td colspan="2">
							<obs conceptId="162207" rows="2" cols="50" style="textarea" />
						</td>
					</tr>
					<tr>
						<td>${uimessage('codbr.DeathCertificate.fertileAgePregnancy')}</td>
						<td colspan="2">
							<obs conceptId="1523" answerConceptIds="1065,1066,1067" />
						</td>
					</tr>
					<tr>
						<td colspan="4">
							<obs  conceptId="163120" answerConceptIds="163117,163118,163119,1067" style="radio"/>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td >${uimessage('codbr.Death.icdCode')}</td>
			<td colspan="2">
				<obs conceptId="162208"/>
			</td>
		</tr>
		<tr>
			<td >${uimessage('codbr.Death.doctorName')}</td>
			<td colspan="2">
				<obs conceptId="162204"/>
			</td>
		</tr>
		<tr>
			<td >${uimessage('codbr.Death.nmcNo')}</td>
			<td colspan="2">
				<obs conceptId="162209"/>
			</td>
		</tr>
		<tr>
			<td >${uimessage('codbr.date')}</td>
			<td colspan="2">
				<encounterDate default="today"/>
			</td>
		</tr>
	</table>
	</div>
	<submit/>
	<script type="text/javascript">
	if(jQuery) {
	$j(document).ready(function() 
	{
jQuery('#ageYear').hide();
jQuery('#date').hide();
jQuery('#user').hide();
jQuery('#foetal').hide();
jQuery('.nepaliDate').find("input").click
(function() {
createcalendar(this);
});
jQuery('#birthDate').find("input").click
(function() {
try{
//var y = document.getElementsByClassName('nepaliDate');
//var y = document.getElementById("birthDateNepali").value;
var y = document.getElementById("birthDateNepali").innerHTML;
//alert(y);
}catch(e) { alert(e); }
//convertNepalDates(document.getElementById("birthDateNepali").value,this);
});
jQuery('tr[parent-dependancy]').each(function() {
	var parentdepkeyval = jQuery(this).attr('parent-dependancy').split(','); 
	var obj=jQuery(this);
	var map = {};
	for(var i = 0; i &lt; parentdepkeyval.length; i++){
		keyval = parentdepkeyval[i].split(":");
		map[keyval[0]]=keyval[1];
	}
	// queestions are to be shown at some event these should be hidden first
	if(map.action.toLowerCase() == 'show'){
		jQuery(obj).css({"display":"none"});
	}
	try{
	// for applying logic on load
	assessSkips(obj, map, getField(map.parent+'.value'));
	//alert(getValue(map.parent+'.value'));
	//alert(JSON.stringify(getValue(map.parent+'.value')));
	getField(map.parent+'.value').click(function(){
	         assessSkips(obj, map, this);
	});
	}catch(e){alert(map.parent+"::"+e);}
});
   if ( $j.browser.msie ) {
        $j(":checkbox").click(function(){
             $j(this).change();
     });
 }
 $j(".enableDisable").each(function(){
     var group = $j(this);
     function disableFn(){
         group.children("#disabled").fadeTo(250,0.33);
         group.children("#disabled").find(":checkbox").attr("checked",false); //uncheck
         group.children("#disabled").find("input[type$='text']").val("");
         group.children("#disabled").find("input").attr("disabled",true);  //disable
     }
 function enableFn(){
     group.children("#disabled").fadeTo(250,1);
     group.children("#disabled").find("input").attr("disabled",false);
 }
 disableFn();
 $j(this).children("#trigger").find(":checkbox:first").change(function(){
     var checked = $j(this).attr("checked");
     if(checked == true){
          enableFn();
     }else{
         disableFn();
     }
 });
});
 $j(".checkboxGroup").each(function(){
     var group = $j(this);
     var uncheckAll = function(){
         group.find("input[type$='checkbox']").attr("checked",false);
         group.find("input[type$='checkbox']").change();
     }
     var uncheckRadioAndAll = function(){
     group.find("#checkboxAll,#checkboxRadio").find("input[type$='checkbox']").attr("checked",false);
     group.find("#checkboxAll,#checkboxRadio").find("input[type$='checkbox']").change();
 }
 group.find("#checkboxAll").find("input").click(
     /*  This was tricky... A number of things needed to happen
        Basically, This is supposed to treat a group of inputs as if
        were all one big checkbox. It is designed so that a checkbox
         can be next to an input, and the user clicks the input, the
        checkbox checks as well. But, when the user clicks the checkbox,
         the browser marks the checkbox as checked. Therefore, when we check
         if the checkbox is already checked, it always respondes true...
         We needed to have 2 cases: when the clicking action is on the first checkbox
         and when the action is on any other.  */
    function(){
         var flip;
         var checked = $j(this).siblings(":checkbox:first").attr("checked");
         if($j(this).attr("name") == $j(this).parents("#checkboxAll:first").find(":checkbox:first").attr("name")){
             checked = $j(this).attr("checked");
             flip = checked;
         }else{
             flip = !checked;
         }
         if($j(this).attr("type") == "text") if(flip == false) flip = !filp; // this is so the user doesn't go to check the checkbox, then uncheck it when they hit the input.
         uncheckAll();
         $j(this).parents("#checkboxAll:first").find(":checkbox").attr("checked",flip);
         $j(this).parents("#checkboxAll:first").find(":checkbox").change();
     }
 );
 group.find("#checkboxRadio").find("input[type$='checkbox']").click(function(){
     uncheckAll();
     $j(this).siblings("input[type$='checkbox']").attr("checked",false);
     $j(this).attr("checked",true);
     $j(this).change();
 });
 group.find("#checkboxCheckbox").click(
     function(){
         uncheckRadioAndAll();
     }
 );
 });
});
jQuery('#deathDate').change(
function(){
                dob = getValue("birthDate.value");
                dod = getValue("deathDate.value");
		//var dob = jQuery('#birthDate').val();
		//var dod = jQuery('#deathDate').val();
var ds1 = new Date(dob);
var ds2 = new Date(dod);
                 jQuery('#ageYear').text(inMonths(ds1,ds2));
	});
function inMonths(d1, d2) {
	        var d1Y = d1.getFullYear();
	        var d2Y = d2.getFullYear();
	        var d1M = d1.getMonth();
	        var d2M = d2.getMonth();
	        var month = (d2M+12*d2Y)-(d1M+12*d1Y);
	        var year = Math.floor(month / 12);
  if( year >=1 ){
  jQuery('#foetal').hide();
}else{
 jQuery('#foetal').show();
}
     return year;
	    }
}
function assessSkips(obj, map, parent){
//alert(val);
var resetText;
var resetValue;
try{
    resetText = map.requiredText != null &amp;&amp; map.requiredText != ''
					&amp;&amp; jQuery(parent).find("option:selected").text().toLowerCase() == map.requiredText.toLowerCase();
	resetValue = map.requiredValue != null &amp;&amp; map.requiredValue != ''
					&amp;&amp; jQuery(parent).val().toLowerCase() == map.requiredValue.toLowerCase();
}
catch(e){
//alert(e);
// INCASE OF DATA DISPLAY FORM
 resetText = map.requiredText != null &amp;&amp; map.requiredText != ''
					&amp;&amp; getValue(map.parent+'.value').toLowerCase() == map.requiredText.toLowerCase();
}
	if(map.action.toLowerCase() == 'show'){
		if(resetText){
			jQuery(obj).show();
		}
		else if(resetValue){
			jQuery(obj).show();
		}
		else{
			jQuery('#'+map.resetField).val('');
			jQuery(obj).hide();
		}
	}
	else if(map.action.toLowerCase() == 'hide'){
		if(resetText){
			jQuery(obj).hide();
		}
		else if(resetValue){
			jQuery(obj).hide();
		}
		else{
			jQuery('#'+map.resetField).val('');
			jQuery(obj).show();
		}
	}
}
function calculateAandB() {
    var displayVal = getValue("deathDate.value") - getValue("birthDate.value");
    //$j('#calculated-value').html(displayVal);
    jQuery('#ageYear').html(displayVal);
}
getField("birthDate.value").change(calculateAandB);
getField("deathDate.value").change(calculateAandB);
</script>
</htmlform>